export default {
    key:'Text',
    name:'文本组件',
    props:{
        txt:{
            label:'文本内容',
            default:''
        },
    },
    styles:{
        width:'100%',
        height:'100%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        color:'white',
        background:'black',
        fontSize:'16px',
        fontWeight:'bold',
        textAlign:'center',
        lineHeight:'1.5',
        borderRadius:'5px',
        padding:'10px',
        boxSizing:'border-box',
        overflow:'hidden',
        whiteSpace:'nowrap',
        textOverflow:'ellipsis',
    }
}
