/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./views/visual-editor/components/Layout/Aside/index.vue')['default']
    AttrEditor: typeof import('./views/visual-editor/components/AttrEditor/index.vue')['default']
    AttrsEditor: typeof import('./views/visual-editor/components/AttrsEditor/index.vue')['default']
    BasePackages: typeof import('./views/visual-editor/components/Packages/BasePackages/index.vue')['default']
    BusinesPackages: typeof import('./views/visual-editor/components/Packages/BusinesPackages/index.vue')['default']
    BusinessPackages: typeof import('./views/visual-editor/components/Packages/BusinessPackages/index.vue')['default']
    Button: typeof import('./views/visual-editor/components/Packages/BasePackages/Button.vue')['default']
    CenterEditor: typeof import('./views/visual-editor/components/CenterEditor/index.vue')['default']
    ContainerPackages: typeof import('./views/visual-editor/components/Packages/ContainerPackages/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./views/visual-editor/components/Layout/Header/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./views/visual-editor/components/Packages/BasePackages/Image.vue')['default']
    Layout: typeof import('./views/visual-editor/components/Layout/index.vue')['default']
    NavBar: typeof import('./views/visual-editor/components/Packages/BasePackages/NavBar.vue')['default']
    NoticeBar: typeof import('./views/visual-editor/components/Packages/BasePackages/NoticeBar.vue')['default']
    Packages: typeof import('./views/visual-editor/components/Packages/index.vue')['default']
    PageEditor: typeof import('./views/visual-editor/components/PageEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swipe: typeof import('./views/visual-editor/components/Packages/BasePackages/Swipe.vue')['default']
    Tabbar: typeof import('./views/visual-editor/components/Packages/BasePackages/Tabbar.vue')['default']
    TabBar: typeof import('./views/visual-editor/components/Packages/BasePackages/TabBar.vue')['default']
    Text: typeof import('./views/visual-editor/components/Packages/BasePackages/Text.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
